name: api_up42
channels:
  - conda-forge
  - defaults
dependencies:
  - pyopenssl
  - python=3.10
  - requests
  - sat-search
  - geopandas
  - rasterio
  - fiona
  - pip:
      - geojson
      - shapely
      - python-multipart
      - fastapi
      - "uvicorn[standard]"
      - pytest
      - numpy
      - httpx
